// <copyright file="AskAnExpertCardPayload.cs" company="Games For Seva">
// Copyright (c) Games For Seva. All rights reserved.
// </copyright>

namespace YICG.Apps.Teams.DigitalKnowBot.Common.Models
{
    /// <summary>
    /// Represents the submit data associated with the Ask An Expert card.
    /// </summary>
    public class AskAnExpertCardPayload : TeamsAdaptiveSubmitActionData
    {
        /// <summary>
        /// Gets or sets the user title text for the ask an expert card.
        /// </summary>
        public string Title { get; set; }

        /// <summary>
        /// Gets or sets the question for the expert being asked by the user through the bot command.
        /// </summary>
        public string Description { get; set; }

        /// <summary>
        /// Gets or sets the question for the expert being asked by the user through the Response Card-
        /// Response Card: Response generated by the bot to the user question by calling the QnA Maker Service.
        /// </summary>
        public string UserQuestion { get; set; }

        /// <summary>
        /// Gets or sets the answer for the expert- Answer sent to the SME team along with the feedback
        /// provided by the user on response given by the bot after calling the QnA Maker Service.
        /// </summary>
        public string KnowledgeBaseAnswer { get; set; }
    }
}