//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YICG.Apps.Teams.DigitalKnowBot.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("YICG.Apps.Teams.DigitalKnowBot.Properties.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If I return an answer which is not what you&apos;re looking for, you can always ask an expert to help..
        /// </summary>
        public static string AskAGuideContent {
            get {
                return ResourceManager.GetString("AskAGuideContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ask an expert.
        /// </summary>
        public static string AskAGuideHeader {
            get {
                return ResourceManager.GetString("AskAGuideHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can answer the questions from the end users and satisfy the knowledge seekers..
        /// </summary>
        public static string EndUserCardContent {
            get {
                return ResourceManager.GetString("EndUserCardContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Users.
        /// </summary>
        public static string EndUserCardHeader {
            get {
                return ResourceManager.GetString("EndUserCardHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can ask a question about this game, _Ganga River Rescue_ and I&apos;ll do my best to answer it!.
        /// </summary>
        public static string FunctionCardContent {
            get {
                return ResourceManager.GetString("FunctionCardContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ask a question ❓❓❓.
        /// </summary>
        public static string FunctionCardHeader {
            get {
                return ResourceManager.GetString("FunctionCardHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Each time you assign tickets, the end user will recieve a notification..
        /// </summary>
        public static string NotificationsCardContent {
            get {
                return ResourceManager.GetString("NotificationsCardContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notifications.
        /// </summary>
        public static string NotificationsCardHeader {
            get {
                return ResourceManager.GetString("NotificationsCardHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I encourage you to share more feedback about how I&apos;m doing, so that I can help you better in the future..
        /// </summary>
        public static string ShareFeedbackContent {
            get {
                return ResourceManager.GetString("ShareFeedbackContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share Feedback.
        /// </summary>
        public static string ShareFeedbackHeader {
            get {
                return ResourceManager.GetString("ShareFeedbackHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team Tour.
        /// </summary>
        public static string TakeATeamTourButtonText {
            get {
                return ResourceManager.GetString("TakeATeamTourButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take a tour!.
        /// </summary>
        public static string TakeATourButtonText {
            get {
                return ResourceManager.GetString("TakeATourButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here you can assign tickets, and also mark them closed once a proper solution has been reached..
        /// </summary>
        public static string TicketSystemTeamContent {
            get {
                return ResourceManager.GetString("TicketSystemTeamContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ticketing System.
        /// </summary>
        public static string TicketSystemTeamHeader {
            get {
                return ResourceManager.GetString("TicketSystemTeamHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hi! I’m the Ganga River Rescue Bot! If you want to know more about what I do, click on _Take a tour_ below..
        /// </summary>
        public static string UserWelcomeCardContent {
            get {
                return ResourceManager.GetString("UserWelcomeCardContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Hello!_ 👋👋👋.
        /// </summary>
        public static string UserWelcomeCardHeader {
            get {
                return ResourceManager.GetString("UserWelcomeCardHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello team! I&apos;m going to help you with understanding the tickets, assigning them, and connecting you to the knowledge seekers to the end users. To learn more, click on _Take A Tour_..
        /// </summary>
        public static string WelcomeTeamCardContent {
            get {
                return ResourceManager.GetString("WelcomeTeamCardContent", resourceCulture);
            }
        }
    }
}
